2025-01-10 01:12:30,524 | INFO | Starting easy-search with command:

/home/almalinux/merizo_search/merizo_search/merizo.py easy-search /home/almalinux/AF-P43341-F1-model_v4.pdb /home/almalinux/cath_foldclassdb/cath-4.3-foldclassdb /home/almalinux/spark_out/AF-P43341-F1-model_v4.pdb tmp --iterate --output_headers -d cpu --threads 1

Traceback (most recent call last):
  File "/home/almalinux/merizo_search/merizo_search/merizo.py", line 443, in <module>
    main()
  File "/home/almalinux/merizo_search/merizo_search/merizo.py", line 436, in main
    easy_search(args)
  File "/home/almalinux/merizo_search/merizo_search/merizo.py", line 367, in easy_search
    search_results, all_search_results = dbsearch(
  File "/home/almalinux/merizo_search/merizo_search/programs/Foldclass/dbsearch.py", line 491, in run_dbsearch
    target_db = read_database(db_name=db_name, device=device)
  File "/home/almalinux/merizo_search/merizo_search/programs/Foldclass/dbsearch.py", line 51, in read_database
    target_db = torch.load(db_name + '.pt').to(device)
  File "/home/almalinux/merizosearch_env/lib64/python3.9/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/almalinux/merizosearch_env/lib64/python3.9/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory